Config = {
  ["UsingLoader"]     = false,
  
  ["UsingESX"]        = true,
  ["UsingESX_V1.2.0"] = false,
  ["UsingKashacters"] = false,
  ["CashAccountName"] = "money",
  ["BankAccountName"] = "bank",
}

Controls = {
Focus = 185,
Grab = 24,
}

furni = {}

furni.objects = {
["Opbevaring"] = {
  [1] = { ["object"] = "prop_fruit_basket", ["price"] = 45, ["name"] = "Kurv" },
  [2] = { ["object"] = "prop_cs_sack_01", ["price"] = 50, ["name"] = "Sæk" },
  [3] = { ["object"] = "prop_tool_box_01", ["price"] = 200, ["name"] = "Tool Box 01" },
  [4] = { ["object"] = "prop_tool_box_02", ["price"] = 200, ["name"] = "Tool Box 02" },
  [5] = { ["object"] = "prop_tool_box_03", ["price"] = 100, ["name"] = "Tool Box 03" },
  [6] = { ["object"] = "prop_tool_box_04", ["price"] = 150, ["name"] = "Tool Box 04" },
  [7] = { ["object"] = "prop_crate_03a", ["price"] = 100, ["name"] = "Trækasse 01" },
  [8] = { ["object"] = "prop_crate_float_1", ["price"] = 100, ["name"] = "Trækasse 02" },
  [9] = { ["object"] = "prop_crate_04a", ["price"] = 100, ["name"] = "Trækasse 03" },
  [10] = { ["object"] = "prop_crate_05a", ["price"] = 200, ["name"] = "Trækasse 04" },
  [11] = { ["object"] = "prop_crate_06a", ["price"] = 200, ["name"] = "Trækasse 05" },
  [12] = { ["object"] = "prop_crate_07a", ["price"] = 250, ["name"] = "Trækasse 06" },
  [13] = { ["object"] = "prop_cratepile_03a", ["price"] = 200, ["name"] = "Trækasse 07" },
  [14] = { ["object"] = "prop_cratepile_07a", ["price"] = 1000, ["name"] = "Trækasse 08" },
  [15] = { ["object"] = "prop_idol_case_01", ["price"] = 50, ["name"] = "Trækasse 09" },
  [16] = { ["object"] = "prop_crate_11a", ["price"] = 150, ["name"] = "Ølkasse 01" },
  [17] = { ["object"] = "prop_crate_11c", ["price"] = 150, ["name"] = "Ølkasse 02" },
  [18] = { ["object"] = "prop_crate_11b", ["price"] = 150, ["name"] = "Sodavandskasse 01" },
  [19] = { ["object"] = "prop_crate_11d", ["price"] = 150, ["name"] = "Sodavandskasse 02" },
  [20] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 300, ["name"] = "Fletkurv" },
  [21] = { ["object"] = "prop_devin_box_closed", ["price"] = 300, ["name"] = "Box 01" },
  [22] = { ["object"] = "prop_mil_crate_02", ["price"] = 450, ["name"] = "Box 02" },
  [23] = { ["object"] = "prop_mil_crate_01", ["price"] = 600, ["name"] = "Box 03" },
  [24] = { ["object"] = "prop_drop_armscrate_01b", ["price"] = 500, ["name"] = "Box 04" },
  [25] = { ["object"] = "prop_drop_crate_01", ["price"] = 500, ["name"] = "Box 05" },
  [26] = { ["object"] = "prop_drop_crate_01_set", ["price"] = 4500, ["name"] = "Box 06" },
  [27] = { ["object"] = "prop_drop_crate_01_set2", ["price"] = 3750, ["name"] = "Box 07" },
  [28] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 2300, ["name"] = "Safe 01" },
  [29] = { ["object"] = "v_res_cabinet", ["price"] = 5000, ["name"] = "Kommode 01" },
  [30] = { ["object"] = "v_res_d_sideunit", ["price"] = 900, ["name"] = "Kommonde 02" },
  [31] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 10000, ["name"] = "Kommode 03" },
  [32] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 8000, ["name"] = "Kommode 04" },
  [33] = { ["object"] = "v_res_mconsolemod", ["price"] = 7000, ["name"] = "Kommode 05" },
  [34] = { ["object"] = "v_res_mcupboard", ["price"] = 900, ["name"] = "Kommode 06" },
  [35] = { ["object"] = "v_res_mdchest", ["price"] = 1900, ["name"] = "Kommode 07" },
  [36] = { ["object"] = "v_res_m_armoire", ["price"] = 2200, ["name"] = "Kommode 08" },
  [37] = { ["object"] = "v_res_tre_storageunit", ["price"] = 1800, ["name"] = "Kommode 09" },
  [38] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 1100, ["name"] = "Kommode 10" },
  [39] = { ["object"] = "v_med_p_sideboard", ["price"] = 2500, ["name"] = "Kommode 11" },
  [40] = { ["object"] = "v_med_bench1", ["price"] = 1800, ["name"] = "Kommode 12" },
  [41] = { ["object"] = "v_res_msoncabinet", ["price"] = 12000, ["name"] = "TV reol" },
  [42] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 1200, ["name"] = "Reol" },
  [43] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 2000, ["name"] = "Skab" },
  [44] = { ["object"] = "v_res_tre_storagebox", ["price"] = 1000, ["name"] = "Kiste" },
  [45] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Klædeskab" },
  [46] = { ["object"] = "v_med_apecrate", ["price"] = 2500, ["name"] = "Abe bur 01" },
  [47] = { ["object"] = "v_med_apecratelrg", ["price"] = 5500, ["name"] = "Abe bur 02" },
  [48] = { ["object"] = "v_med_cor_filingcab", ["price"] = 900, ["name"] = "Dokument kabinet" },
},


["Stole"] = {
  [1] = { ["object"] = "prop_skid_chair_01", ["price"] = 250, ["name"] = "Klapstol 01" },
  [2] = { ["object"] = "prop_skid_chair_02", ["price"] = 250, ["name"] = "Klapstol 02" },
  [3] = { ["object"] = "prop_skid_chair_03", ["price"] = 250, ["name"] = "Klapstol 03" },
  [4] = { ["object"] = "prop_direct_chair_02", ["price"] = 300, ["name"] = "Klapstol 04" },
  [5] = { ["object"] = "prop_direct_chair_01", ["price"] = 300, ["name"] = "Klapstol 05" },
  [6] = { ["object"] = "v_ilev_tort_stool", ["price"] = 250, ["name"] = "Skammel 01" },
  [7] = { ["object"] = "v_ret_ta_stool", ["price"] = 150, ["name"] = "Skammel 02" },
  [8] = { ["object"] = "v_med_cor_medstool", ["price"] = 200, ["name"] = "Skammel 03" },
  [9] = { ["object"] = "v_res_j_stool", ["price"] = 200, ["name"] = "Fodskammel 01" },
  [10] = { ["object"] = "prop_bar_stool_01", ["price"] = 400, ["name"] = "Barstol 01" },
  [11] = { ["object"] = "prop_stool_01", ["price"] = 500, ["name"] = "Barstol 02" },
  [12] = { ["object"] = "v_ilev_fh_kitchenstool", ["price"] = 1000, ["name"] = "Barstol 03" },
  [13] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 1000, ["name"] = "Barstol 04" },
  [14] = { ["object"] = "v_ret_gc_chair01", ["price"] = 900, ["name"] = "Barstol 05" },
  [15] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "Barstol 06" },
  [16] = { ["object"] = "v_res_tre_stool", ["price"] = 150, ["name"] = "Barstol 07" },
  [17] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 200, ["name"] = "Barstol 08" },
  [18] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 150, ["name"] = "Barstol 09" },
  [19] = { ["object"] = "prop_table_08_chr", ["price"] = 2000, ["name"] = "Bænk" },
  [20] = { ["object"] = "v_res_mbottoman", ["price"] = 1600, ["name"] = "Opbevaringsbænk 01" },
  [21] = { ["object"] = "v_corp_facebeanbag", ["price"] = 400, ["name"] = "Sækkestol" },
  [22] = { ["object"] = "prop_table_03b_chr", ["price"] = 75, ["name"] = "Spisebordsstol 01" },
  [23] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "Spisebordsstol 02" },
  [24] = { ["object"] = "v_res_fa_chair02", ["price"] = 110, ["name"] = "Spisebordsstol 03" },
  [25] = { ["object"] = "v_res_fa_chair01", ["price"] = 130, ["name"] = "Spisebordsstol 04" },
  [26] = { ["object"] = "v_res_j_dinechair", ["price"] = 120, ["name"] = "Spisebordsstol 05" },
  [27] = { ["object"] = "v_res_m_dinechair", ["price"] = 175, ["name"] = "Spisebordsstol 06" },
  [28] = { ["object"] = "prop_table_03_chr", ["price"] = 150, ["name"] = "Spisebordsstol 07" },
  [29] = { ["object"] = "v_res_study_chair", ["price"] = 200, ["name"] = "Spisebordsstol 08" },
  [30] = { ["object"] = "v_res_tre_chair", ["price"] = 220, ["name"] = "Spisebordsstol 09" },
  [31] = { ["object"] = "v_res_trev_framechair", ["price"] = 210, ["name"] = "Spisebordsstol 10" },
  [32] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 400, ["name"] = "Spisebordsstol 11" },
  [33] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 400, ["name"] = "Spisebordsstol 12" },
  [34] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 400, ["name"] = "Spisebordsstol 13" },
  [35] = { ["object"] = "prop_table_02_chr", ["price"] = 500, ["name"] = "Spisebordsstol 14" },
  [36] = { ["object"] = "prop_table_01_chr_a", ["price"] = 500, ["name"] = "Spisebordsstol 15" },
  [37] = { ["object"] = "prop_table_01_chr_b", ["price"] = 500, ["name"] = "Spisebordsstol 16" },
  [38] = { ["object"] = "v_ilev_m_dinechair", ["price"] = 650, ["name"] = "Spisebordsstol 17" },
  [39] = { ["object"] = "prop_table_04_chr", ["price"] = 700, ["name"] = "Spisebordsstol 18" },
  [40] = { ["object"] = "prop_table_05_chr", ["price"] = 750, ["name"] = "Spisebordsstol 19" },
  [41] = { ["object"] = "v_ilev_fh_dineeamesa", ["price"] = 1500, ["name"] = "Spisebordsstol 20" },
  [42] = { ["object"] = "prop_yacht_seat_03", ["price"] = 1000, ["name"] = "Spisebordsstol 21" },
  [43] = { ["object"] = "v_res_mbchair", ["price"] = 1400, ["name"] = "Spisebordsstol 22" },
  [44] = { ["object"] = "v_med_p_deskchair", ["price"] = 400, ["name"] = "Spisebordsstol 23" },
  [45] = { ["object"] = "v_ret_chair_white", ["price"] = 1700, ["name"] = "Spisebordsstol 24" },
  [46] = { ["object"] = "v_ret_chair", ["price"] = 1600, ["name"] = "Spisebordsstol 25" },
  [47] = { ["object"] = "v_ilev_p_easychair", ["price"] = 1200, ["name"] = "Loungestol 01" },
  [48] = { ["object"] = "p_ilev_p_easychair_s", ["price"] = 1200, ["name"] = "Loungestol 02" },
  [49] = { ["object"] = "prop_waiting_seat_01", ["price"] = 1500, ["name"] = "Loungestol 03" },
  [50] = { ["object"] = "prop_yacht_seat_01", ["price"] = 1000, ["name"] = "Loungestol 04" },
  [51] = { ["object"] = "v_res_fh_barcchair", ["price"] = 1400, ["name"] = "Loungestol 05" },
  [52] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Loungestol 06" },
  [53] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Lænestol 01" },
  [54] = { ["object"] = "p_armchair_01_s", ["price"] = 1200, ["name"] = "Lænestol 02" },
  [55] = { ["object"] = "v_res_fh_singleseat", ["price"] = 1100, ["name"] = "Lænestol 03" },
  [56] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Lænestol 04" },
  [57] = { ["object"] = "v_res_m_armchair", ["price"] = 1600, ["name"] = "Lænestol 05" },
  [58] = { ["object"] = "v_med_whickerchair1", ["price"] = 450, ["name"] = "Lænestol 06" },
  [59] = { ["object"] = "v_med_p_easychair", ["price"] = 900, ["name"] = "Lænestol 07" },
  [60] = { ["object"] = "v_res_mp_stripchair", ["price"] = 800, ["name"] = "Lænestol 08" },
  [61] = { ["object"] = "v_res_d_armchair", ["price"] = 350, ["name"] = "Lænestol 09" },
  [62] = { ["object"] = "prop_yacht_lounger", ["price"] = 1200, ["name"] = "Liggestol 01" },
  [63] = { ["object"] = "v_corp_cd_chair", ["price"] = 500, ["name"] = "Kontorstol 01" },
  [64] = { ["object"] = "p_clb_officechair_s", ["price"] = 350, ["name"] = "Kontorstol 02" },
  [65] = { ["object"] = "v_res_tre_officechair", ["price"] = 100, ["name"] = "Kontorstol 03" },
  [66] = { ["object"] = "v_corp_bk_chair3", ["price"] = 750, ["name"] = "Kontorstol 04" },
  [67] = { ["object"] = "v_ret_gc_chair03", ["price"] = 1150, ["name"] = "Kontorstol 05" },
  [68] = { ["object"] = "v_club_officechair", ["price"] = 1250, ["name"] = "Kontorstol 06" },
  [69] = { ["object"] = "v_ilev_leath_chr", ["price"] = 1450, ["name"] = "Kontorstol 07" },
  [70] = { ["object"] = "v_corp_offchair", ["price"] = 1500, ["name"] = "Kontorstol 08" },
  [71] = { ["object"] = "p_soloffchair_s", ["price"] = 1500, ["name"] = "Kontorstol 09" },
  [72] = { ["object"] = "prop_sol_chair", ["price"] = 1500, ["name"] = "Kontorstol 10" },
  [73] = { ["object"] = "v_ilev_hd_chair", ["price"] = 100, ["name"] = "Barber Stol" },
  [74] = { ["object"] = "v_med_hospseating1", ["price"] = 1600, ["name"] = "Venteplads" },
},


["Sofaer"] = {
  [1] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "Puf 01" },
  [2] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 350, ["name"] = "Puf 02" },
  [3] = { ["object"] = "v_res_fh_pouf", ["price"] = 250, ["name"] = "Puf 03" },
  [4] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "2 Personers sofa 01" },
  [5] = { ["object"] = "prop_rub_couch02", ["price"] = 300, ["name"] = "2 Personers sofa 02" },
  [6] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 400, ["name"] = "2 Personers sofa 03" },
  [7] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 300, ["name"] = "2 Personers sofa 04" },
  [8] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 450, ["name"] = "2 Personers sofa 05" },
  [9] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 600, ["name"] = "2 Personers sofa 06" },
  [10] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "2 Personers sofa 07" },
  [11] = { ["object"] = "prop_yacht_seat_02", ["price"] = 1000, ["name"] = "2 Personers sofa 08" },
  [12] = { ["object"] = "p_res_sofa_l_s", ["price"] = 1500, ["name"] = "2 Personers sofa 09" },
  [13] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 2100, ["name"] = "2 Personers sofa 10" },
  [14] = { ["object"] = "v_res_r_sofa", ["price"] = 1800, ["name"] = "2 Personers sofa 11" },
  [15] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "2 Personers sofa 12" },
  [16] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 400, ["name"] = "3 Personers sofa 01" },
  [17] = { ["object"] = "v_res_tt_sofa", ["price"] = 650, ["name"] = "3 Personers sofa 02" },
  [18] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "3 Personers sofa 03" },
  [19] = { ["object"] = "p_v_med_p_sofa_s", ["price"] = 2000, ["name"] = "3 Personers sofa 04" },
  [20] = { ["object"] = "v_res_j_sofa", ["price"] = 500, ["name"] = "3 Personers sofa 05" },
  [21] = { ["object"] = "v_ilev_m_sofa", ["price"] = 2500, ["name"] = "Chaiselong sofa 01" },
  [22] = { ["object"] = "p_lev_sofa_s", ["price"] = 2500, ["name"] = "Chaiselong sofa 02" },
  [23] = { ["object"] = "v_res_mp_sofa", ["price"] = 12000, ["name"] = "Hjørnesofa 01" },
  [24] = { ["object"] = "v_res_fh_sofa", ["price"] = 12000, ["name"] = "Hjørnesofa 02" },
  [25] = { ["object"] = "prop_wait_bench_01", ["price"] = 750, ["name"] = "Daybed 01" },
  [26] = { ["object"] = "prop_t_sofa", ["price"] = 1500, ["name"] = "Daybed 02" },
},


["Borde"] = {
  [1] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 100, ["name"] = "Sidebord 01" },
  [2] = { ["object"] = "v_res_j_lowtable", ["price"] = 150, ["name"] = "Sidebord 02" },
  [3] = { ["object"] = "v_res_tre_sideboard", ["price"] = 400, ["name"] = "Sidebord 03" },
  [4] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "Sidebord 04" },
  [5] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Sengebord 01" },
  [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 800, ["name"] = "Sengebord 02" },
  [7] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 900, ["name"] = "Sengebord 03" },
  [8] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 900, ["name"] = "Sengebord 04" },
  [9] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Sengebord 05" },
  [10] = { ["object"] = "prop_table_07", ["price"] = 150, ["name"] = "Cafebord 01" },
  [11] = { ["object"] = "v_res_d_roundtable", ["price"] = 300, ["name"] = "Cafebord 02" },
  [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Cafebord 03" },
  [13] = { ["object"] = "prop_tea_trolly", ["price"] = 600, ["name"] = "Rullebord 01" },
  [14] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 200, ["name"] = "Rullebord 02" },
  [15] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "Rullebord 03" },
  [16] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 400, ["name"] = "Rullebord 04" },
  [17] = { ["object"] = "prop_tool_bench02", ["price"] = 1800, ["name"] = "Arbejdsbord 01" },
  [18] = { ["object"] = "prop_tool_bench02_ld", ["price"] = 1700, ["name"] = "Arbejdsbord 02" },
  [19] = { ["object"] = "prop_rub_table_01", ["price"] = 800, ["name"] = "Arbejdsbord 03" },
  [20] = { ["object"] = "prop_rub_table_02", ["price"] = 1200, ["name"] = "Arbejdsbord 04" },
  [21] = { ["object"] = "v_med_benchcentr", ["price"] = 7500, ["name"] = "Køkkenbord 01" },
  [22] = { ["object"] = "prop_t_coffe_table", ["price"] = 1400, ["name"] = "Sofabord 01" },
  [23] = { ["object"] = "prop_t_coffe_table_02", ["price"] = 1800, ["name"] = "Sofabord 02" },
  [24] = { ["object"] = "v_res_d_coffeetable", ["price"] = 600, ["name"] = "Sofabord 03" },
  [25] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Sofabord 04" },
  [26] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Sofabord 05" },
  [27] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Sofabord 06" },
  [28] = { ["object"] = "v_res_j_coffeetable", ["price"] = 800, ["name"] = "Sofabord 07" },
  [29] = { ["object"] = "v_res_m_stool", ["price"] = 700, ["name"] = "Sofabord 08" },
  [30] = { ["object"] = "v_med_p_coffeetable", ["price"] = 1600, ["name"] = "Sofabord 09" },
  [31] = { ["object"] = "v_med_hosptable", ["price"] = 600, ["name"] = "Sofabord 10" },
  [32] = { ["object"] = "prop_table_08", ["price"] = 6000, ["name"] = "Spisebord 01" },
  [33] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 12000, ["name"] = "Spisebord 02" },
  [34] = { ["object"] = "prop_table_05", ["price"] = 3000, ["name"] = "Spisebord 03" },
  [35] = { ["object"] = "prop_table_08_side", ["price"] = 2500, ["name"] = "Spisebord 04" },
  [36] = { ["object"] = "prop_table_01", ["price"] = 1300, ["name"] = "Spisebord 05" },
  [37] = { ["object"] = "prop_table_02", ["price"] = 4800, ["name"] = "Spisebord 06" },
  [38] = { ["object"] = "prop_table_03", ["price"] = 1100, ["name"] = "Spisebord 07" },
  [39] = { ["object"] = "prop_table_03b", ["price"] = 750, ["name"] = "Spisebord 08" },
  [40] = { ["object"] = "prop_table_04", ["price"] = 3000, ["name"] = "Spisebord 09" },
  [41] = { ["object"] = "v_res_fh_diningtable", ["price"] = 5000, ["name"] = "Spisebord 10" },
  [42] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 1100, ["name"] = "Spisebord 11" },
  [43] = { ["object"] = "v_ret_csr_table", ["price"] = 600, ["name"] = "Spisebord 12" },
  [44] = { ["object"] = "hei_heist_din_table_06", ["price"] = 7000, ["name"] = "Spisebordsaet 01" },
  [45] = { ["object"] = "prop_yacht_table_01", ["price"] = 500, ["name"] = "Yacht bord 01" },
  [46] = { ["object"] = "prop_yacht_table_02", ["price"] = 900, ["name"] = "Yacht bord 02" },
  [47] = { ["object"] = "prop_yacht_table_03", ["price"] = 1200, ["name"] = "Yacht bord 03" },
  [48] = { ["object"] = "p_new_j_counter_01", ["price"] = 6000, ["name"] = "Disk 01" },
  [49] = { ["object"] = "p_new_j_counter_02", ["price"] = 1500, ["name"] = "Disk 02" },
  [50] = { ["object"] = "p_new_j_counter_02", ["price"] = 9000, ["name"] = "Disk 03" },
  [51] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Skrivebord 01" },
  [52] = { ["object"] = "v_med_p_desk", ["price"] = 2000, ["name"] = "Skrivebord 02" },
  [53] = { ["object"] = "v_res_mbdresser", ["price"] = 1400, ["name"] = "Skrivebord 03" },
  [54] = { ["object"] = "v_med_bench2", ["price"] = 1600, ["name"] = "Skrivebord 04" },
  [55] = { ["object"] = "v_res_son_desk", ["price"] = 9000, ["name"] = "Skrivebordssæt" },
  [56] = { ["object"] = "v_res_m_console", ["price"] = 1200, ["name"] = "Konsolbord 01" },
  [57] = { ["object"] = "v_res_m_h_console", ["price"] = 1800, ["name"] = "Konsolbord 02" },
  [58] = { ["object"] = "v_res_tre_tvstand", ["price"] = 700, ["name"] = "TV bord 01" },
  [59] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 1100, ["name"] = "TV bord 02" },
  [60] = { ["object"] = "v_res_j_tvstand", ["price"] = 400, ["name"] = "Tv bord 03" },
  [61] = { ["object"] = "v_res_mddresser", ["price"] = 1200, ["name"] = "Sminkebord 01" },
  [62] = { ["object"] = "v_res_d_dressingtable", ["price"] = 800, ["name"] = "Sminkebord 02" },
  [63] = { ["object"] = "v_res_m_sidetable", ["price"] = 600, ["name"] = "Sminkebord 03" },
  [64] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 20000, ["name"] = "Obduktionsbord 01" },
  [65] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 1800, ["name"] = "Obduktionsbord 02" },
},


["Senge"] = {
  [1] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "Seng 01" },
  [2] = { ["object"] = "v_med_bed1", ["price"] = 1200, ["name"] = "Seng 02" },
  [3] = { ["object"] = "v_med_bed2", ["price"] = 1500, ["name"] = "Seng 03" },
  [4] = { ["object"] = "v_res_tt_bed", ["price"] = 1000, ["name"] = "3/4 seng 01" },
  [5] = { ["object"] = "p_v_res_tt_bed_s", ["price"] = 1000, ["name"] = "3/4 seng 02" },
  [6] = { ["object"] = "v_res_msonbed", ["price"] = 4000, ["name"] = "3/4 seng 03" },
  [7] = { ["object"] = "v_res_msonbed_s", ["price"] = 4000, ["name"] = "3/4 seng 04" },
  [8] = { ["object"] = "v_res_tre_bed1", ["price"] = 2000, ["name"] = "3/4 seng 05" },
  [9] = { ["object"] = "v_res_tre_bed2", ["price"] = 3000, ["name"] = "3/4 seng 06" },
  [10] = { ["object"] = "v_res_d_bed", ["price"] = 3400, ["name"] = "3/4 seng 07" },
  [11] = { ["object"] = "p_mbbed_s", ["price"] = 5000, ["name"] = "Dobbeltseng 01" },
  [12] = { ["object"] = "v_res_mbbed", ["price"] = 5000, ["name"] = "Dobbeltseng 02" },
  [13] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 6000, ["name"] = "Dobbeltseng 03" }, 
  [14] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 8000, ["name"] = "Dobbeltseng 04" },
  [15] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 10000, ["name"] = "Dobbeltseng 05" },
  [16] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 12000, ["name"] = "Dbbeltseng 06" },
},


["Belysning"] = {
  [1] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Flickering Light" },
  [2] = { ["object"] = "v_res_d_lampa", ["price"] = 400, ["name"] = "Bordlampe 01" },
  [3] = { ["object"] = "v_ilev_fh_lampa_on", ["price"] = 400, ["name"] = "Bordlampe 02" },
  [4] = { ["object"] = "hei_prop_hei_bnk_lamp_01", ["price"] = 150, ["name"] = "Bordlampe 03" },
  [5] = { ["object"] = "hei_prop_hei_bnk_lamp_02", ["price"] = 550, ["name"] = "Bordlampe 04" },
  [6] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 200, ["name"] = "Bordlampe 05" },
  [7] = { ["object"] = "v_res_desklamp", ["price"] = 150, ["name"] = "Bordlampe 06" },
  [8] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 120, ["name"] = "Bordlampe 07" },
  [9] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 300, ["name"] = "Bordlampe 08" },
  [10] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 400, ["name"] = "Bordlampe 09" },
  [11] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 150, ["name"] = "Bordlampe 10" },
  [12] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Bordlampe 11" },
  [13] = { ["object"] = "v_res_mtblelampmod", ["price"] = 200, ["name"] = "Bordlampe 12" },
  [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 180, ["name"] = "Bordlampe 13" },
  [15] = { ["object"] = "v_ret_gc_lamp", ["price"] = 150, ["name"] = "Bordlampe 14" },
  [16] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 150, ["name"] = "Væglampe 01" },
  [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 180, ["name"] = "Væglampe 02" },
  [18] = { ["object"] = "hei_prop_bank_ornatelamp", ["price"] = 400, ["name"] = "Loftslampe 01" },
  [19] = { ["object"] = "v_res_tre_lightfan", ["price"] = 700, ["name"] = "Loftslampe 02" },
  [20] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 800, ["name"] = "Gulvlampe 01" },
  [21] = { ["object"] = "v_res_m_lampstand", ["price"] = 400, ["name"] = "Gulvlampe 02" },
  [22] = { ["object"] = "v_res_m_lampstand2", ["price"] = 450, ["name"] = "Gulvlampe 03" },
  [23] = { ["object"] = "v_res_tre_talllamp", ["price"] = 400, ["name"] = "Gulvlampe 04" },
  [24] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Lysskab" },
  [25] = { ["object"] = "v_med_examlight", ["price"] = 1400, ["name"] = "Exam lys" },
},


["Elektronik"] = {
  [1] = { ["object"] = "v_res_fa_fan", ["price"] = 400, ["name"] = "Blæser" },
  [2] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Gulv blæser 01" },
  [3] = { ["object"] = "v_res_fh_towerfan", ["price"] = 500, ["name"] = "Gulv blæser 02" },
  [4] = { ["object"] = "v_ret_ta_camera", ["price"] = 300, ["name"] = "Kamera" },
  [5] = { ["object"] = "prop_cs_cctv", ["price"] = 400, ["name"] = "Overvaagnings kamera" },
  [6] = { ["object"] = "hei_prop_hei_bio_panel", ["price"] = 1000, ["name"] = "Panel 01" },
  [7] = { ["object"] = "prop_ld_keypad_01", ["price"] = 1200, ["name"] = "Panel 02" },
  [8] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 1300, ["name"] = "Panel 03" },
  [9] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 100, ["name"] = "Vækkeur 01" },
  [10] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Vækkeur 02" },
  [11] = { ["object"] = "prop_tv_05", ["price"] = 300, ["name"] = "TV 01" },
  [12] = { ["object"] = "prop_tv_test", ["price"] = 300, ["name"] = "TV 02" },
  [13] = { ["object"] = "prop_tv_04", ["price"] = 400, ["name"] = "TV 03" },
  [14] = { ["object"] = "prop_tv_02", ["price"] = 500, ["name"] = "TV 04" },
  [15] = { ["object"] = "prop_tv_01", ["price"] = 500, ["name"] = "TV 05" },
  [16] = { ["object"] = "prop_tv_03", ["price"] = 600, ["name"] = "TV 06" },
  [17] = { ["object"] = "prop_tv_06", ["price"] = 700, ["name"] = "TV 07" },
  [18] = { ["object"] = "prop_trev_tv_01", ["price"] = 1000, ["name"] = "Fladskærm 01" },
  [19] = { ["object"] = "prop_tv_flat_02", ["price"] = 1200, ["name"] = "Fladskærm 02" },
  [20] = { ["object"] = "prop_tv_flat_03", ["price"] = 1200, ["name"] = "Fladskærm 03" },
  [21] = { ["object"] = "prop_tv_flat_02b", ["price"] = 1500, ["name"] = "Fladskærm 04" },
  [22] = { ["object"] = "prop_tv_flat_03b", ["price"] = 1700, ["name"] = "Fladskærm 05" },
  [23] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 5000, ["name"] = "Fladskærm 06" },
  [24] = { ["object"] = "prop_tv_flat_01", ["price"] = 6000, ["name"] = "Fladskærm 07" },
  [25] = { ["object"] = "prop_tv_03_overlay", ["price"] = 1000, ["name"] = "Fladskærm 08" },
  [26] = { ["object"] = "prop_tv_flat_01_screen", ["price"] = 6000, ["name"] = "Fladskærm 09" },
  [27] = { ["object"] = "prop_michaels_credit_tv", ["price"] = 1200, ["name"] = "Fladskærm 10" },
  [28] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 1100, ["name"] = "Fladskærm 11" },
  [29] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 7000, ["name"] = "TV set 01" },
  [30] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 5000, ["name"] = "TV set 02" },
  [31] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 4000, ["name"] = "TV set 03" },
  [32] = { ["object"] = "v_med_cor_tvstand", ["price"] = 900, ["name"] = "TV Set 04" },
  [33] = { ["object"] = "prop_cs_remote_01", ["price"] = 150, ["name"] = "Fjernbetjening" },
  [34] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 500, ["name"] = "VHS afspiller" },
  [35] = { ["object"] = "prop_cs_dvd_player", ["price"] = 750, ["name"] = "DVD afspiller" },
  [36] = { ["object"] = "prop_vcr_01", ["price"] = 1000, ["name"] = "VCR afspiller" },
  [37] = { ["object"] = "v_res_mountedprojector", ["price"] = 4000, ["name"] = "Projector 01" },
  [38] = { ["object"] = "v_ilev_acet_projector", ["price"] = 2000, ["name"] = "Projector 02" },
  [39] = { ["object"] = "v_ilev_mm_screen", ["price"] = 1500, ["name"] = "Projector lærred 01" },
  [40] = { ["object"] = "v_ilev_mm_screen2", ["price"] = 2200, ["name"] = "Projector lærred 02" },
  [41] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 1800, ["name"] = "Projector lærred 03" },
  [42] = { ["object"] = "v_ret_gc_phone", ["price"] = 300, ["name"] = "Telefon 01" },
  [43] = { ["object"] = "v_res_fa_phone", ["price"] = 150, ["name"] = "Telefon 02" },
  [44] = { ["object"] = "prop_cs_tablet_02", ["price"] = 8000, ["name"] = "Tablet 01" },
  [45] = { ["object"] = "prop_cs_tablet", ["price"] = 7000, ["name"] = "Tablet 02" },
  [46] = { ["object"] = "prop_ld_lap_top", ["price"] = 2000, ["name"] = "Bærbar 01" },
  [47] = { ["object"] = "p_amb_lap_top_02", ["price"] = 3000, ["name"] = "Bærbar 02" },
  [48] = { ["object"] = "p_amb_lap_top_02", ["price"] = 5000, ["name"] = "Apple bærbar" },
  [49] = { ["object"] = "prop_mouse_01a", ["price"] = 200, ["name"] = "Mus 01" },
  [50] = { ["object"] = "prop_mouse_01b", ["price"] = 300, ["name"] = "Mus 02" },
  [51] = { ["object"] = "v_res_mousemat", ["price"] = 500, ["name"] = "Mus 03" },
  [52] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 500, ["name"] = "Computer keyboard" },
  [53] = { ["object"] = "v_serv_ct_monitor07", ["price"] = 1000, ["name"] = "Computer skærm 01" },
  [54] = { ["object"] = "v_serv_ct_monitor06", ["price"] = 1000, ["name"] = "Computer skærm 02" },
  [55] = { ["object"] = "v_serv_ct_monitor05", ["price"] = 1000, ["name"] = "Computer skærm 03" },
  [56] = { ["object"] = "v_serv_ct_monitor04", ["price"] = 1000, ["name"] = "Computer skærm 04" },
  [57] = { ["object"] = "v_serv_ct_monitor03", ["price"] = 1000, ["name"] = "Computer skærm 05" },
  [58] = { ["object"] = "v_serv_ct_monitor02", ["price"] = 1000, ["name"] = "Computer skærm 06" },
  [59] = { ["object"] = "v_serv_ct_monitor01", ["price"] = 1000, ["name"] = "Computer skærm 07" },
  [60] = { ["object"] = "prop_ld_monitor_01", ["price"] = 1000, ["name"] = "Computer skærm 08" },
  [61] = { ["object"] = "v_res_monitorsquare", ["price"] = 1000, ["name"] = "Computer skærm 09" },
  [62] = { ["object"] = "prop_monitor_li", ["price"] = 2000, ["name"] = "Computer skærm 10" },
  [63] = { ["object"] = "prop_monitor_w_large", ["price"] = 2500, ["name"] = "Computer skærm 11" },
  [64] = { ["object"] = "prop_monitor_04a", ["price"] = 3000, ["name"] = "Computer skærm 12" },
  [65] = { ["object"] = "v_res_lest_monitor", ["price"] = 1500, ["name"] = "Computer skærm 13" }, 
  [66] = { ["object"] = "prop_dyn_pc_02", ["price"] = 9000, ["name"] = "Computer" },
  [67] = { ["object"] = "v_med_benchset1", ["price"] = 22000, ["name"] = "Computer/Hjertemåler" },
  [68] = { ["object"] = "prop_till_02", ["price"] = 2500, ["name"] = "Kasseapperat 01" },
  [69] = { ["object"] = "prop_till_01", ["price"] = 3000, ["name"] = "Kasseapperat 02" },
  [70] = { ["object"] = "prop_till_01_dam", ["price"] = 3000, ["name"] = "Kasseapperat 03" },
  [71] = { ["object"] = "prop_till_03", ["price"] = 3500, ["name"] = "Kasseapperat 04" },
  [72] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 3000, ["name"] = "Kasseapperat 05" },
  [73] = { ["object"] = "prop_sewing_machine", ["price"] = 150, ["name"] = "Symaskine" },
  [74] = { ["object"] = "v_med_centrifuge1", ["price"] = 10000, ["name"] = "Mixer" },
  [75] = { ["object"] = "v_med_cooler", ["price"] = 9000, ["name"] = "Køler" },
  [76] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Vægt" },
  [77] = { ["object"] = "v_med_oscillator3", ["price"] = 8000, ["name"] = "Hjertemåler" },
},


["Hvidevarer"] = {
  [1] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Minikøleskab" },
  [2] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 300, ["name"] = "Køle-fryseskab 01" },
  [3] = { ["object"] = "prop_trailr_fridge", ["price"] = 1000, ["name"] = "Køle-fryseskab 02" },
  [4] = { ["object"] = "prop_fridge_03", ["price"] = 1500, ["name"] = "Køle-fryseskab 03" },
  [5] = { ["object"] = "prop_fridge_01", ["price"] = 2000, ["name"] = "Køle-fryseskab 04" },
  [6] = { ["object"] = "v_ilev_mm_fridgeint", ["price"] = 3500, ["name"] = "Køle-fryseskab 05" },
  [7] = { ["object"] = "v_res_fridgemodsml", ["price"] = 4000, ["name"] = "Køle-fryseskab 06" },
  [8] = { ["object"] = "v_res_fridgemoda", ["price"] = 6000, ["name"] = "Køle-fryseskab 07" },
  [9] = { ["object"] = "prop_vend_fridge01", ["price"] = 2500, ["name"] = "Køleskab" },
  [10] = { ["object"] = "prop_cooker_03", ["price"] = 5000, ["name"] = "Komfur" },
  [11] = { ["object"] = "prop_micro_01", ["price"] = 300, ["name"] = "Microbølgeovn 01" },
  [12] = { ["object"] = "prop_micro_04", ["price"] = 400, ["name"] = "Microbølgeovn 02" },
  [13] = { ["object"] = "prop_micro_02", ["price"] = 500, ["name"] = "Microbølgeovn 03" },
  [14] = { ["object"] = "prop_micro_cs_01", ["price"] = 500, ["name"] = "Microbølgeovn 04" },
  [15] = { ["object"] = "v_ret_fh_dryer", ["price"] = 4000, ["name"] = "Tørretumbler" },
  [16] = { ["object"] = "prop_washer_01", ["price"] = 400, ["name"] = "Vaskemaskine 01" },
  [17] = { ["object"] = "prop_washer_03", ["price"] = 750, ["name"] = "Vaskemaskine 02" },
  [18] = { ["object"] = "prop_washer_02", ["price"] = 1100, ["name"] = "Vaskemaskine 03" },
  [19] = { ["object"] = "v_ret_fh_washmach", ["price"] = 4000, ["name"] = "Vaskemaskine 04" },
},


["Køkken"] = {
  [1] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Skærebræt" },
  [2] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Redskaber" },
  [3] = { ["object"] = "prop_bonesaw", ["price"] = 300, ["name"] = "Knoglesav" },
  [4] = { ["object"] = "v_res_pestle", ["price"] = 100, ["name"] = "Morter" },
  [5] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "Køkkenrulle 01" },
  [6] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "Køkkenrulle 02" },
  [7] = { ["object"] = "v_res_tt_mug01", ["price"] = 20, ["name"] = "Krus" },
  [8] = { ["object"] = "v_ret_fh_plate3", ["price"] = 25, ["name"] = "Tallerken 01" },
  [9] = { ["object"] = "v_res_tt_pizzaplate", ["price"] = 30, ["name"] = "Tallerken 02" },
  [10] = { ["object"] = "v_ret_fh_plate2", ["price"] = 50, ["name"] = "Tallerken 03" },
  [11] = { ["object"] = "v_ret_fh_plate4", ["price"] = 50, ["name"] = "Tallerken 04" },
  [12] = { ["object"] = "v_ret_fh_plate1", ["price"] = 50, ["name"] = "Tallerken 05" },
  [13] = { ["object"] = "v_res_mplatesml", ["price"] = 75, ["name"] = "Tallerken 06" },
  [14] = { ["object"] = "v_res_tt_bowlpile02", ["price"] = 120, ["name"] = "Skåle samling" },
  [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 45, ["name"] = "Kande" },
  [16] = { ["object"] = "v_res_r_teapot", ["price"] = 200, ["name"] = "Te kande" },
  [17] = { ["object"] = "prop_pot_05", ["price"] = 100, ["name"] = "Stegepande" },
  [18] = { ["object"] = "prop_wok", ["price"] = 200, ["name"] = "Wok" },
  [19] = { ["object"] = "v_ret_fh_pot05", ["price"] = 50, ["name"] = "Gryde 01" },
  [20] = { ["object"] = "v_ret_fh_pot01", ["price"] = 75, ["name"] = "Gryde 02" },
  [21] = { ["object"] = "v_ret_fh_pot02", ["price"] = 100, ["name"] = "Gryde 03" },
  [22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Gryde 04" },
  [23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Gryde 05" },
  [24] = { ["object"] = "prop_pot_rack", ["price"] = 650, ["name"] = "Gryde samling" },
  [25] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Æggeur" },
  [26] = { ["object"] = "watercooler_bottle001", ["price"] = 100, ["name"] = "Vandbeholder" },
  [27] = { ["object"] = "prop_watercooler", ["price"] = 600, ["name"] = "Vandkøler 01" },
  [28] = { ["object"] = "prop_watercooler_dark", ["price"] = 600, ["name"] = "Vandkøler 02" },
  [29] = { ["object"] = "prop_kitch_juicer", ["price"] = 500, ["name"] = "Juicer" },
  [30] = { ["object"] = "prop_toaster_02", ["price"] = 100, ["name"] = "Toastmaskine 01" },
  [31] = { ["object"] = "prop_toaster_01", ["price"] = 150, ["name"] = "Toastmaskine 02" },
  [32] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Elkeddel" },
  [33] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Vægt" },
  [34] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Køkkenmaskine" },
},


["Badeværelse"] = {
  [1] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 20, ["name"] = "Kleenex 01" },
  [2] = { ["object"] = "v_res_tissues", ["price"] = 30, ["name"] = "Kleenex 02" },
  [3] = { ["object"] = "v_med_cor_papertowels", ["price"] = 600, ["name"] = "Papir dispenser" },
  [4] = { ["object"] = "v_res_r_perfume", ["price"] = 450, ["name"] = "Parfume" },
  [5] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 550, ["name"] = "Aftershave" },
  [6] = { ["object"] = "v_res_r_lotion", ["price"] = 120, ["name"] = "Bodyotion 01" },
  [7] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 40, ["name"] = "Bodyotion 02" },
  [8] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 40, ["name"] = "Ansigtscreme" },
  [9] = { ["object"] = "v_hair_d_bcream", ["price"] = 210, ["name"] = "Hårvoks 01" },
  [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 50, ["name"] = "Hårvoks 02" },
  [11] = { ["object"] = "v_hair_d_gel", ["price"] = 170, ["name"] = "Hårgel" },
  [12] = { ["object"] = "v_haird_mousse", ["price"] = 110, ["name"] = "Hårmousse" },
  [13] = { ["object"] = "v_hair_d_shave", ["price"] = 100, ["name"] = "Barberingscreme" },
  [14] = { ["object"] = "prop_toilet_shamp_01", ["price"] = 40, ["name"] = "Shampoo 01" },
  [15] = { ["object"] = "prop_toilet_shamp_02", ["price"] = 70, ["name"] = "Shampoo 02" },
  [16] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 40, ["name"] = "Shampoo 03" },
  [17] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 40, ["name"] = "Håndsæbe" },
  [18] = { ["object"] = "prop_toothbrush_01", ["price"] = 30, ["name"] = "Tandbørste" },
  [19] = { ["object"] = "prop_ld_health_pack", ["price"] = 60, ["name"] = "Førstehjælpstaske" },
  [20] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 90, ["name"] = "Førstehjælpskasse" },
  [21] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 50, ["name"] = "Hostesaft" },
  [22] = { ["object"] = "prop_cs_script_bottle", ["price"] = 40, ["name"] = "Piller" },
  [23] = { ["object"] = "prop_shower_rack_01", ["price"] = 120, ["name"] = "Brusehylde" },
  [24] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Håndklæde 01" },
  [25] = { ["object"] = "prop_towel_01", ["price"] = 120, ["name"] = "Håndklæde 02" },
  [26] = { ["object"] = "v_res_mbtowelfld", ["price"] = 120, ["name"] = "Håndklæde 03" },
  [27] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Håndklædeholder 01" },
  [28] = { ["object"] = "prop_towel_rail_01", ["price"] = 200, ["name"] = "Håndklædeholder 02" },
  [29] = { ["object"] = "prop_soap_disp_01", ["price"] = 80, ["name"] = "Sæbe dispenser" },
  [30] = { ["object"] = "prop_handdry_01", ["price"] = 125, ["name"] = "Papir dispenser" },
  [31] = { ["object"] = "prop_handdry_02", ["price"] = 250, ["name"] = "Håndblæser" },
  [32] = { ["object"] = "prop_ld_toilet_01", ["price"] = 200, ["name"] = "Toilet 01" },
  [33] = { ["object"] = "prop_toilet_02", ["price"] = 300, ["name"] = "Toilet 02" },
  [34] = { ["object"] = "prop_toilet_01", ["price"] = 500, ["name"] = "Toilet 03" },
  [35] = { ["object"] = "prop_sink_05", ["price"] = 300, ["name"] = "Håndvask 01" },
  [36] = { ["object"] = "prop_sink_06", ["price"] = 600, ["name"] = "Håndvask 02" },
  [37] = { ["object"] = "prop_sink_02", ["price"] = 900, ["name"] = "Håndvask 03" },
  [38] = { ["object"] = "prop_sink_04", ["price"] = 1200, ["name"] = "Håndvask 04" },
  [39] = { ["object"] = "v_res_mbsink", ["price"] = 1800, ["name"] = "Håndvask 05" },    
  [40] = { ["object"] = "v_res_mbath", ["price"] = 6000, ["name"] = "Badekar" },
},


["Rengøring"] = {
  [1] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Vaskekurv 01" },
  [2] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 350, ["name"] = "Vaksekurv 02" },
  [3] = { ["object"] = "prop_blox_spray", ["price"] = 50, ["name"] = "Rengøringsmiddel" },
  [4] = { ["object"] = "prop_floor_duster_01", ["price"] = 150, ["name"] = "Moppe" },
  [5] = { ["object"] = "prop_f_duster_02", ["price"] = 150, ["name"] = "Støv moppe" },
  [6] = { ["object"] = "prop_cs_ironing_board", ["price"] = 150, ["name"] = "Strygebræt" },
  [7] = { ["object"] = "zprop_bin_01a_old", ["price"] = 100, ["name"] = "Skraldespand 01" },
  [8] = { ["object"] = "v_ret_gc_bin", ["price"] = 50, ["name"] = "Skraldespand 02" },
  [9] = { ["object"] = "v_ret_csr_bin", ["price"] = 50, ["name"] = "Skraldespand 03" },
  [10] = { ["object"] = "v_res_mbbin", ["price"] = 75, ["name"] = "Skraldespand 04" },
  [11] = { ["object"] = "v_res_tre_bin", ["price"] = 120, ["name"] = "Skraldespand 05" },
  [12] = { ["object"] = "v_med_bin", ["price"] = 200, ["name"] = "Skraldespand 06" },
  [13] = { ["object"] = "v_med_cor_cembin", ["price"] = 150, ["name"] = "Skraldespand 07" },
  [14] = { ["object"] = "v_med_medwastebin", ["price"] = 300, ["name"] = "Skraldespand 08" },
  [15] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 30, ["name"] = "Skraldepose" },
  [16] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Gummi hansker" },  
},


["Planter"] = {
  [1] = { ["object"] = "prop_cs_fertilizer", ["price"] = 30, ["name"] = "Plante gødning" },
  [2] = { ["object"] = "p_single_rose_s", ["price"] = 30, ["name"] = "Blomster 01" },
  [3] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 180, ["name"] = "Blomster 02" },
  [4] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 200, ["name"] = "Blomster 03" },
  [5] = { ["object"] = "v_res_fh_flowersa", ["price"] = 400, ["name"] = "Blomster 04" },
  [6] = { ["object"] = "v_res_mflowers", ["price"] = 450, ["name"] = "Blomster 05" },
  [7] = { ["object"] = "v_res_mvasechinese", ["price"] = 350, ["name"] = "Blomster 06" }, 
  [8] = { ["object"] = "v_ret_flowers", ["price"] = 200, ["name"] = "Blomster 07" },
  [9] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 200, ["name"] = "Blomster 08" },
  [10] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 200, ["name"] = "Blomster 09" },
  [11] = { ["object"] = "prop_fib_plant_01", ["price"] = 250, ["name"] = "Grøn plante 01" },
  [12] = { ["object"] = "prop_plant_int_04b", ["price"] = 250, ["name"] = "Grøn plante 02" },
  [13] = { ["object"] = "p_int_jewel_plant_02", ["price"] = 300, ["name"] = "Grøn plante 03" },
  [14] = { ["object"] = "p_int_jewel_plant_01", ["price"] = 300, ["name"] = "Grøn plante 04" },
  [15] = { ["object"] = "prop_fbibombplant", ["price"] = 250, ["name"] = "Grøn plante 05" },
  [16] = { ["object"] = "prop_plant_int_01a", ["price"] = 400, ["name"] = "Grøn plante 06" },
  [17] = { ["object"] = "prop_plant_int_01b", ["price"] = 400, ["name"] = "Grøn plante 07" },
  [18] = { ["object"] = "prop_plant_int_03a", ["price"] = 250, ["name"] = "Grøn plante 08" },
  [19] = { ["object"] = "prop_plant_int_03b", ["price"] = 250, ["name"] = "Grøn plante 09" },
  [20] = { ["object"] = "prop_plant_int_03c", ["price"] = 250, ["name"] = "Grøn plante 10" },
  [21] = { ["object"] = "prop_plant_int_04a", ["price"] = 350, ["name"] = "Grøn plante 11" },
  [22] = { ["object"] = "prop_plant_int_04c", ["price"] = 100, ["name"] = "Grøn plante 12" },
  [23] = { ["object"] = "prop_plant_palm_01a", ["price"] = 180, ["name"] = "Grøn plante 13" },
  [24] = { ["object"] = "prop_pot_plant_01a", ["price"] = 130, ["name"] = "Grøn plante 14" },
  [25] = { ["object"] = "prop_pot_plant_01b", ["price"] = 150, ["name"] = "Grøn plante 15" },
  [26] = { ["object"] = "prop_pot_plant_01c", ["price"] = 200, ["name"] = "Grøn plante 16" },
  [27] = { ["object"] = "prop_pot_plant_01d", ["price"] = 250, ["name"] = "Grøn plante 17" },
  [28] = { ["object"] = "prop_pot_plant_01e", ["price"] = 150, ["name"] = "Grøn plante 18" },
  [29] = { ["object"] = "prop_pot_plant_03c", ["price"] = 150, ["name"] = "Grøn plante 19" },
  [30] = { ["object"] = "prop_pot_plant_05b", ["price"] = 350, ["name"] = "Grøn plante 20" },
  [31] = { ["object"] = "v_res_mplanttongue", ["price"] = 300, ["name"] = "Grøn plante 21" },
  [32] = { ["object"] = "v_corp_bombplant", ["price"] = 400, ["name"] = "Grøn plante 22" }, 
  [33] = { ["object"] = "v_res_m_bananaplant", ["price"] = 900, ["name"] = "Grøn plante 23" }, 
  [34] = { ["object"] = "v_res_m_palmplant1", ["price"] = 1100, ["name"] = "Grøn plante 24" },
  [35] = { ["object"] = "v_res_m_palmstairs", ["price"] = 1100, ["name"] = "Grøn plante 25" },
  [36] = { ["object"] = "v_res_m_urn", ["price"] = 400, ["name"] = "Grøn plante 26" },
  [37] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Grøn plante 27" }, 
  [38] = { ["object"] = "v_res_tre_plant", ["price"] = 600, ["name"] = "Grøn plante 28" }, 
  [39] = { ["object"] = "v_res_tre_tree", ["price"] = 400, ["name"] = "Grøn plante 29" },  
  [40] = { ["object"] = "v_med_p_planter", ["price"] = 300, ["name"] = "Grøn plante 30" }, 
  [41] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 500, ["name"] = "Juletræ 01" },
  [42] = { ["object"] = "prop_xmas_tree_int", ["price"] = 500, ["name"] = "Juletræ 02" },
},


["Kunst/Ophæng"] = {
  [1] = { ["object"] = "prop_hotel_clock_01", ["price"] = 400, ["name"] = "Vægur 01" },
  [2] = { ["object"] = "prop_v_15_cars_clock", ["price"] = 200, ["name"] = "Vægur 02" },
  [3] = { ["object"] = "prop_v_5_bclock", ["price"] = 200, ["name"] = "Vægur 03" },
  [4] = { ["object"] = "prop_game_clock_01", ["price"] = 250, ["name"] = "Vægur 04" },
  [5] = { ["object"] = "prop_game_clock_02", ["price"] = 300, ["name"] = "Vægur 05" },
  [6] = { ["object"] = "prop_sm_19_clock", ["price"] = 300, ["name"] = "Vægur 06" },
  [7] = { ["object"] = "prop_sports_clock_01", ["price"] = 200, ["name"] = "Vægur 07" },
  [8] = { ["object"] = "v_ret_gc_clock", ["price"] = 200, ["name"] = "Vægur 08" },
  [9] = { ["object"] = "v_res_mchalkbrd", ["price"] = 200, ["name"] = "Tavle 01" },
  [10] = { ["object"] = "prop_b_board_blank", ["price"] = 800, ["name"] = "Tavle 02" },
  [11] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 500, ["name"] = "Maleri 1" },
  [12] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 500, ["name"] = "Maleri 2" },
  [13] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 500, ["name"] = "Maleri 3" },
  [14] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 500, ["name"] = "Maleri 4" },
  [15] = { ["object"] = "v_ilev_ra_doorsafe", ["price"] = 500, ["name"] = "Maleri 5" },
  [16] = { ["object"] = "v_ilev_trev_pictureframe", ["price"] = 100, ["name"] = "Ramme" },
  [17] = { ["object"] = "v_ilev_trev_pictureframebroken", ["price"] = 150, ["name"] = "Billede 01" },
  [18] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 300, ["name"] = "Billede 02" },
  [19] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 1800, ["name"] = "Statue" },
  [20] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 2000, ["name"] = "Skulptur" },
  [21] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Dødningehoved" },
  [22] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 450, ["name"] = "Gardin" },
},


["Figurer og legetøj"] = {
  [1] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Figur 01" },
  [2] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Figur 02" },
  [3] = { ["object"] = "v_res_r_figcat", ["price"] = 100, ["name"] = "Figur 03" },
  [4] = { ["object"] = "v_res_r_figclown", ["price"] = 200, ["name"] = "Figer 04" },
  [5] = { ["object"] = "v_res_r_figfemale", ["price"] = 200, ["name"] = "Figur 05" },
  [6] = { ["object"] = "v_res_r_figflamenco", ["price"] = 200, ["name"] = "Figur 06" },
  [7] = { ["object"] = "v_res_r_figgirl", ["price"] = 150, ["name"] = "Figur 07" },
  [8] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 200, ["name"] = "Figur 08" },
  [9] = { ["object"] = "v_res_r_figoblisk", ["price"] = 200, ["name"] = "Figur 09" },
  [10] = { ["object"] = "v_res_r_figpillar", ["price"] = 200, ["name"] = "Figur 10" },
  [11] = { ["object"] = "v_res_d_ramskull", ["price"] = 150, ["name"] = "Dyrekranium" },
  [12] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Bamse" },
  [13] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 50, ["name"] = "Dukke" },
},


["Pynt"] = {
  [1] = { ["object"] = "prop_binoc_01", ["price"] = 200, ["name"] = "Kikkert" },
  [2] = { ["object"] = "prop_t_telescope_01b", ["price"] = 1000, ["name"] = "Teleskop" },
  [3] = { ["object"] = "prop_cs_dvd", ["price"] = 20, ["name"] = "DVD" },
  [4] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD æske" },
  [5] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 50, ["name"] = "Film rulle" },
  [6] = { ["object"] = "v_res_mbronzvase", ["price"] = 230, ["name"] = "Vase 01" },
  [7] = { ["object"] = "v_res_cherubvase", ["price"] = 1100, ["name"] = "Vase 02" },
  [8] = { ["object"] = "prop_cs_petrol_can", ["price"] = 40, ["name"] = "Benzindunk 01" },
  [9] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Benzindunk 02" },
  [10] = { ["object"] = "prop_cs_katana_01", ["price"] = 300, ["name"] = "Sabel" },
  [11] = { ["object"] = "v_res_fashmagopen", ["price"] = 60, ["name"] = "Magasin 01" },
  [12] = { ["object"] = "v_res_fashmag1", ["price"] = 60, ["name"] = "Magasin 02" },
  [13] = { ["object"] = "v_ret_ta_mag1", ["price"] = 250, ["name"] = "Magasin 03" },
  [14] = { ["object"] = "v_ret_ta_mag2", ["price"] = 250, ["name"] = "Magasin 04" },
  [15] = { ["object"] = "v_res_fa_magtidy", ["price"] = 100, ["name"] = "Magasin beholder 01" },
  [16] = { ["object"] = "v_res_j_magrack", ["price"] = 100, ["name"] = "Magasin beholder 02" },
  [17] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Kurv med indhold" },
  [18] = { ["object"] = "prop_cs_vial_01", ["price"] = 60, ["name"] = "Beholder" },
  [19] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Linth" },
  [20] = { ["object"] = "v_res_m_candle", ["price"] = 200, ["name"] = "Lysestage" },
  [21] = { ["object"] = "v_res_m_candlelrg", ["price"] = 900, ["name"] = "Lysestage stor" },
  [22] = { ["object"] = "v_res_r_figauth2", ["price"] = 150, ["name"] = "Ramme" },
  [23] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Skulptur 01" },   
  [24] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Skulptur 02" }, 
  [25] = { ["object"] = "v_res_sculpt_dece", ["price"] = 600, ["name"] = "Skulptur 03" },
  [26] = { ["object"] = "v_res_sculpt_decf", ["price"] = 2000, ["name"] = "Skulptur 04" },
  [27] = { ["object"] = "v_med_cor_hose", ["price"] = 800, ["name"] = "Vandslange" },
},


["Tekstiler"] = {
  [1] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 1000, ["name"] = "Gulvtæppe 01" },
  [2] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 1000, ["name"] = "Gulvtæppe 02" },
  [3] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 1000, ["name"] = "Gulvtæppe 03" },
  [4] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Hovedpude" },
  [5] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Pyntepude 01" },
  [6] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Pyntepude 02" },
  [7] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Pyntepude 03" },
  [8] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Pyntepude 04" },
  [9] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 200, ["name"] = "Pyntepude 05" },
  [10] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 200, ["name"] = "Pyntepude 06" },
},


["Narkotika"] = {
  [1] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bong 01" },
  [2] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bong 02" },
  [3] = { ["object"] = "prop_drug_package_02", ["price"] = 2000, ["name"] = "Drugs 01" },
  [4] = { ["object"] = "hei_prop_hei_drug_pack_02", ["price"] = 2000, ["name"] = "Drugs 02" },
  [5] = { ["object"] = "prop_drug_package", ["price"] = 5000, ["name"] = "Drugs 03" },
  [6] = { ["object"] = "hei_prop_hei_drug_pack_01b", ["price"] = 5000, ["name"] = "Drugs 04" },
  [7] = { ["object"] = "hei_prop_hei_drug_case", ["price"] = 15000, ["name"] = "Drugs 05" },
  [8] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Kemikaler 01" },
  [9] = { ["object"] = "v_med_cor_chemical", ["price"] = 200, ["name"] = "Kemikaler 02" },
  [10] = { ["object"] = "v_med_cor_wallunita", ["price"] = 6000, ["name"] = "Kemikaler 03" },
  [11] = { ["object"] = "v_med_gastank", ["price"] = 4000, ["name"] = "Gas Tank" },
},


["Sexlegetøj"] = {
  [1] = { ["object"] = "prop_porn_mag_01", ["price"] = 70, ["name"] = "Magasin 01" },
  [2] = { ["object"] = "prop_porn_mag_02", ["price"] = 70, ["name"] = "Magasin 02" },
  [3] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 50, ["name"] = "Håndjern" },
  [4] = { ["object"] = "prop_cs_dildo_01", ["price"] = 200, ["name"] = "Vibrator 01" },
  [5] = { ["object"] = "v_res_d_dildo_a", ["price"] = 500, ["name"] = "Vibrator 02" },
  [6] = { ["object"] = "v_res_d_dildo_b", ["price"] = 600, ["name"] = "Vibrator 03" },
  [7] = { ["object"] = "v_res_d_dildo_c", ["price"] = 400, ["name"] = "Vibrator 04" },
  [8] = { ["object"] = "v_res_d_lube", ["price"] = 150, ["name"] = "Anal glidecreme" },
  [9] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Piske samling" },
  [10] = { ["object"] = "v_res_d_paddedwall", ["price"] = 1100, ["name"] = "SM væg" },
},


["Kontor"] = {
  [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 25, ["name"] = "A4 papir 01" },
  [2] = { ["object"] = "prop_barry_table_detail", ["price"] = 45, ["name"] = "A4 papir 02" },
  [3] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Tegnesæt" },
  [4] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["name"] = "Organizer 01" },
  [5] = { ["object"] = "v_ret_gc_trays", ["price"] = 100, ["name"] = "Organizer 02" },
  [6] = { ["object"] = "prop_cs_stock_book", ["price"] = 50, ["name"] = "Bog 01" },
  [7] = { ["object"] = "v_ret_ta_book4", ["price"] = 50, ["name"] = "Bog 02" },
  [8] = { ["object"] = "v_ret_ta_book1", ["price"] = 50, ["name"] = "Bog 03" },
  [9] = { ["object"] = "v_ret_ta_book2", ["price"] = 50, ["name"] = "Bog 04" },
  [10] = { ["object"] = "v_ret_ta_book3", ["price"] = 50, ["name"] = "Bog 05" },
  [11] = { ["object"] = "v_res_cdstorage", ["price"] = 75, ["name"] = "CD'er" },
  [12] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "Skål med breve" },
  [13] = { ["object"] = "prop_cs_binder_01", ["price"] = 50, ["name"] = "Mappe 01" },
  [14] = { ["object"] = "v_ret_gc_folder1", ["price"] = 60, ["name"] = "Mappe 02" },
  [15] = { ["object"] = "v_ret_gc_folder2", ["price"] = 60, ["name"] = "Mappe 03" },
  [16] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 15, ["name"] = "Konvolut" },
  [17] = { ["object"] = "v_res_paperfolders", ["price"] = 110, ["name"] = "Dokumenter" },
  [18] = { ["object"] = "v_ret_gc_trays", ["price"] = 80, ["name"] = "Bakke" },
  [19] = { ["object"] = "prop_cs_lester_crate", ["price"] = 80, ["name"] = "Kasse 01" },
  [20] = { ["object"] = "v_res_officeboxfile01", ["price"] = 60, ["name"] = "Kasse 02" },
  [21] = { ["object"] = "v_res_filebox01", ["price"] = 60, ["name"] = "Kasse 03" },
  [22] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 60, ["name"] = "Kasse 04" },
  [23] = { ["object"] = "v_ret_gc_print", ["price"] = 500, ["name"] = "Printer 01" },
  [24] = { ["object"] = "v_med_cor_photocopy", ["price"] = 3000, ["name"] = "Printer 02" },
  [25] = { ["object"] = "v_ret_gc_shred", ["price"] = 450, ["name"] = "Krydsmakulator" },
  [26] = { ["object"] = "prop_w_board_blank", ["price"] = 1000, ["name"] = "Whiteboard 01" },
  [27] = { ["object"] = "prop_w_board_blank_2", ["price"] = 1000, ["name"] = "Whiteboard 02" },
},


["Tøj, sko og accessories"] = {
  [1] = { ["object"] = "prop_aviators_01", ["price"] = 500, ["name"] = "Solbriller" },
  [2] = { ["object"] = "v_res_jewelbox", ["price"] = 175, ["name"] = "Smykke æske" },
  [3] = { ["object"] = "prop_jewel_03a", ["price"] = 1000, ["name"] = "Ring 01" },
  [4] = { ["object"] = "prop_jewel_03b", ["price"] = 1000, ["name"] = "Ring 02" },
  [5] = { ["object"] = "prop_jewel_04a", ["price"] = 5000, ["name"] = "Ring samling 01" },
  [6] = { ["object"] = "prop_jewel_04b", ["price"] = 5000, ["name"] = "Ring samling 02" },
  [7] = { ["object"] = "prop_j_disptray_01b", ["price"] = 8000, ["name"] = "Ring samling 03" },
  [8] = { ["object"] = "prop_j_disptray_02", ["price"] = 16000, ["name"] = "Ring samling 04" },
  [9] = { ["object"] = "prop_j_disptray_01", ["price"] = 35000, ["name"] = "Smykke samling 01" },
  [10] = { ["object"] = "prop_j_disptray_04", ["price"] = 10000, ["name"] = "Smykke samling 02" },
  [11] = { ["object"] = "prop_j_disptray_04b", ["price"] = 11000, ["name"] = "Smykke samling 03" },
  [12] = { ["object"] = "prop_j_disptray_05", ["price"] = 12000, ["name"] = "Smykke samling 04" },
  [13] = { ["object"] = "prop_j_disptray_05b", ["price"] = 9000, ["name"] = "Smykke samling 05" },
  [14] = { ["object"] = "prop_jewel_02a", ["price"] = 1500, ["name"] = "Armbåndsur 01" },
  [15] = { ["object"] = "prop_jewel_02b", ["price"] = 1500, ["name"] = "Armbåndsur 02" },
  [16] = { ["object"] = "prop_jewel_02c", ["price"] = 1500, ["name"] = "Armbåndsur 03" },
  [17] = { ["object"] = "p_watch_01", ["price"] = 1500, ["name"] = "Armbåndsur 04" },
  [18] = { ["object"] = "p_watch_02", ["price"] = 1300, ["name"] = "Armbåndsur 05" },
  [19] = { ["object"] = "p_watch_03", ["price"] = 1100, ["name"] = "Armbåndsur 06" },
  [20] = { ["object"] = "p_watch_04", ["price"] = 1500, ["name"] = "Armbåndsur 07" },
  [21] = { ["object"] = "p_watch_05", ["price"] = 1500, ["name"] = "Armbåndsur 08" },
  [22] = { ["object"] = "p_watch_06", ["price"] = 1500, ["name"] = "Armbåndsur 09" },
  [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 10000, ["name"] = "Armbåndsur samling" },
  [24] = { ["object"] = "prop_shopping_bags01", ["price"] = 150, ["name"] = "Poser 01" },
  [25] = { ["object"] = "prop_shopping_bags02", ["price"] = 150, ["name"] = "Poser 02" },
  [26] = { ["object"] = "prop_cs_duffel_01", ["price"] = 300, ["name"] = "Taske 01" },
  [27] = { ["object"] = "prop_amb_handbag_01", ["price"] = 200, ["name"] = "Taske 02" },
  [28] = { ["object"] = "prop_ld_handbag", ["price"] = 200, ["name"] = "Taske 03" },
  [29] = { ["object"] = "prop_big_bag_01", ["price"] = 500, ["name"] = "Taske 04" },
  [30] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Taske 05" },
  [31] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 200, ["name"] = "Taske 06" },
  [32] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 500, ["name"] = "Taske 07" },
  [33] = { ["object"] = "v_ret_gc_bag02", ["price"] = 500, ["name"] = "Taske 08" },
  [34] = { ["object"] = "prop_attache_case_01", ["price"] = 150, ["name"] = "Kuffert 01" },
  [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 150, ["name"] = "Kuffert 02"},
  [36] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 300, ["name"] = "Kuffert 03" },
  [37] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 500, ["name"] = "Kuffert 04" },
  [38] = { ["object"] = "prop_tshirt_shelf_2", ["price"] = 500, ["name"] = "Tshirt hylde" },
  [39] = { ["object"] = "prop_dummy_01", ["price"] = 1500, ["name"] = "Mannequin" },
},


["Bar"] = {
  [1] = { ["object"] = "prop_bar_stirrers", ["price"] = 80, ["name"] = "Drink tilbehør 01" },
  [2] = { ["object"] = "prop_bar_drinkstraws", ["price"] = 80, ["name"] = "Drink tilbehør 02" },
  [3] = { ["object"] = "prop_bar_caddy", ["price"] = 200, ["name"] = "Drink tilbehør 03" },
  [4] = { ["object"] = "prop_bar_lemons", ["price"] = 60, ["name"] = "Garnish 01" },
  [5] = { ["object"] = "prop_bar_limes", ["price"] = 60, ["name"] = "Garnish 02" },
  [6] = { ["object"] = "prop_bar_fruit", ["price"] = 85, ["name"] = "Garnish 03" },
  [7] = { ["object"] = "prop_bar_cockshaker", ["price"] = 200, ["name"] = "Cocktail shaker 01" },
  [8] = { ["object"] = "prop_bar_cockshakropn", ["price"] = 150, ["name"] = "Cocktail shaker 02" },
  [9] = { ["object"] = "prop_bar_measrjug", ["price"] = 150, ["name"] = "Målebæger" },
  [10] = { ["object"] = "prop_bar_coastbarr", ["price"] = 10, ["name"] = "Glasbrik 01" },
  [11] = { ["object"] = "prop_bar_coastchamp", ["price"] = 10, ["name"] = "Glasbrik 02" },
  [12] = { ["object"] = "prop_bar_coastdusc", ["price"] = 10, ["name"] = "Glasbrik 03" },
  [13] = { ["object"] = "prop_bar_coastmount", ["price"] = 10, ["name"] = "Glasbrik 04" },
  [14] = { ["object"] = "prop_bar_coastdusc", ["price"] = 150, ["name"] = "Glasbrikker" },
  [15] = { ["object"] = "lts_prop_tumbler_cs2_s2", ["price"] = 25, ["name"] = "Tom lowball glas 01" },
  [16] = { ["object"] = "prop_whiskey_01", ["price"] = 25, ["name"] = "Tom lowball glas 02" },
  [17] = { ["object"] = "prop_whiskey_glasses", ["price"] = 25, ["name"] = "Tom lowball glas 03" },
  [18] = { ["object"] = "prop_tumbler_01_empty", ["price"] = 25, ["name"] = "Tom lowball glas 04" },
  [19] = { ["object"] = "lts_prop_wine_glass_s2", ["price"] = 30, ["name"] = "Tom vinglas 01" },
  [20] = { ["object"] = "prop_champ_flute", ["price"] = 30, ["name"] = "Tom champagne glas 01" },
  [21] = { ["object"] = "prop_cs_champ_flute", ["price"] = 30, ["name"] = "Tom champagne glas 02" },
  [22] = { ["object"] = "p_cs_shot_glass_2_s", ["price"] = 40, ["name"] = "Fyldt shotglas 01" },
  [23] = { ["object"] = "p_cs_shot_glass_s", ["price"] = 40, ["name"] = "Fyldt shotglas 02" },
  [24] = { ["object"] = "lts_prop_tumbler_01_s2", ["price"] = 40, ["name"] = "Fyldt lowball glas 01" },
  [25] = { ["object"] = "p_tumbler_01_bar_s", ["price"] = 40, ["name"] = "Fyldt lowball glas 02" },
  [26] = { ["object"] = "p_tumbler_01_s", ["price"] = 40, ["name"] = "Fyldt lowball glas 03" },
  [27] = { ["object"] = "p_tumbler_01_trev_s", ["price"] = 40, ["name"] = "Fyldt lowball glas 04" },
  [28] = { ["object"] = "p_tumbler_02_s1", ["price"] = 40, ["name"] = "Fyldt lowball glas 05" },
  [29] = { ["object"] = "p_tumbler_cs2_s", ["price"] = 40, ["name"] = "Fyldt lowball glas 06" },
  [30] = { ["object"] = "p_tumbler_cs2_s_day", ["price"] = 40, ["name"] = "Fyldt lowball glas 07" },
  [31] = { ["object"] = "p_tumbler_cs2_s_trev", ["price"] = 40, ["name"] = "Fyldt lowball glas 08" },
  [32] = { ["object"] = "prop_tumbler_01", ["price"] = 40, ["name"] = "Fyldt lowball glas 09" },
  [33] = { ["object"] = "prop_tumbler_01b", ["price"] = 40, ["name"] = "Fyldt lowball glas 10" },
  [34] = { ["object"] = "prop_tumbler_01", ["price"] = 40, ["name"] = "Fyldt lowball glas 11" },
  [35] = { ["object"] = "p_w_grass_gls_s", ["price"] = 40, ["name"] = "Fyldt highball glas 01" },
  [36] = { ["object"] = "prop_tequsunrise", ["price"] = 40, ["name"] = "Fyldt highball glas 02" },
  [37] = { ["object"] = "prop_cocktail", ["price"] = 40, ["name"] = "Fyldt cocktail glas 01" },
  [38] = { ["object"] = "prop_tequila", ["price"] = 40, ["name"] = "Fyldt cocktail glas 02" },
  [39] = { ["object"] = "p_wine_glass_s", ["price"] = 40, ["name"] = "Fyldt rædvin glas" },
  [40] = { ["object"] = "p_champ_flute_s", ["price"] = 40, ["name"] = "Fyldt champagneglas" },
  [41] = { ["object"] = "prop_beggers_sign_03", ["price"] = 200, ["name"] = "Skilt" },
  [42] = { ["object"] = "prop_dart_bd_01", ["price"] = 500, ["name"] = "Dart 01" },
  [43] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 1000, ["name"] = "Dart 02" },
  [44] = { ["object"] = "prop_wooden_barrel", ["price"] = 1000, ["name"] = "Vin tønde" },
  [45] = { ["object"] = "prop_pooltable_02", ["price"] = 6000, ["name"] = "Poolbord 01" },
  [46] = { ["object"] = "prop_pooltable_3b", ["price"] = 6000, ["name"] = "Poolbord 02" },
  [47] = { ["object"] = "prop_table_tennis", ["price"] = 3000, ["name"] = "Bordtennis 01" },
  [48] = { ["object"] = "prop_airhockey_01", ["price"] = 4000, ["name"] = "Airhockey" },
  [49] = { ["object"] = "prop_bball_arcade_01", ["price"] = 4000, ["name"] = "Basket" },
  [50] = { ["object"] = "prop_arcade_01", ["price"] = 3500, ["name"] = "Arcade spillemaskine" },
},


["Alkohol"] = {
  [1] = { ["object"] = "prop_beer_bottle", ["price"] = 50, ["name"] = "Øl flaske 01" },
  [2] = { ["object"] = "prop_beer_am", ["price"] = 50, ["name"] = "Øl flaske 02" },
  [3] = { ["object"] = "prop_beer_jakey", ["price"] = 50, ["name"] = "Øl flaske 03" },
  [4] = { ["object"] = "prop_beer_logger", ["price"] = 50, ["name"] = "Øl flaske 04" },
  [5] = { ["object"] = "prop_beer_logopen", ["price"] = 50, ["name"] = "Øl flaske 05" },
  [6] = { ["object"] = "prop_beer_patriot", ["price"] = 50, ["name"] = "Øl flaske 06" },
  [7] = { ["object"] = "prop_beer_pissh", ["price"] = 50, ["name"] = "Øl flaske 07" },
  [8] = { ["object"] = "prop_beer_pride", ["price"] = 50, ["name"] = "Øl flaske 08" },
  [9] = { ["object"] = "prop_beer_stz", ["price"] = 50, ["name"] = "Øl flaske 09" },
  [10] = { ["object"] = "prop_beer_stzopen", ["price"] = 50, ["name"] = "Øl flaske 10" },
  [11] = { ["object"] = "prop_beerdusche", ["price"] = 50, ["name"] = "Øl flaske 11" },
  [12] = { ["object"] = "prop_beer_blr", ["price"] = 50, ["name"] = "Øl flaske 12" },
  [13] = { ["object"] = "prop_beer_bar", ["price"] = 50, ["name"] = "Øl flaske 13" },
  [14] = { ["object"] = "prop_beer_amopen", ["price"] = 50, ["name"] = "Øl flaske 14" },
  [15] = { ["object"] = "prop_amb_40oz_02", ["price"] = 40, ["name"] = "Øl flaske 15" },
  [16] = { ["object"] = "prop_amb_40oz_03", ["price"] = 40, ["name"] = "Øl flaske 16" },
  [17] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 50, ["name"] = "Øl flaske 17" },
  [18] = { ["object"] = "beerrow_world", ["price"] = 650, ["name"] = "Øl samling 01" },
  [19] = { ["object"] = "beerrow_local", ["price"] = 750, ["name"] = "Øl samling 02" },
  [20] = { ["object"] = "prop_beer_box_01", ["price"] = 850, ["name"] = "Øl kasse 01" },
  [21] = { ["object"] = "prop_cs_beer_box", ["price"] = 500, ["name"] = "Øl kasse 02" },
  [22] = { ["object"] = "prop_wine_bot_02", ["price"] = 100, ["name"] = "Rødvin 01" },
  [23] = { ["object"] = "prop_wine_bot_01", ["price"] = 100, ["name"] = "Rødvin 02" },
  [24] = { ["object"] = "p_cs_bottle_01", ["price"] = 70, ["name"] = "Rødvin 03" },
  [25] = { ["object"] = "prop_wine_rose", ["price"] = 100, ["name"] = "Rosévin" },
  [26] = { ["object"] = "prop_wine_white", ["price"] = 100, ["name"] = "Hvidvin" },
  [27] = { ["object"] = "winerow", ["price"] = 1000, ["name"] = "Vin samling" },
  [28] = { ["object"] = "prop_cava", ["price"] = 200, ["name"] = "Champagne 01" },
  [29] = { ["object"] = "prop_champ_01a", ["price"] = 200, ["name"] = "Champagne 02" },
  [30] = { ["object"] = "prop_champ_01b", ["price"] = 200, ["name"] = "Champagne 03" },
  [31] = { ["object"] = "prop_champ_cool", ["price"] = 200, ["name"] = "Champagne 04" },
  [32] = { ["object"] = "prop_champ_cool", ["price"] = 150, ["name"] = "Champagne 05" },
  [33] = { ["object"] = "prop_champset", ["price"] = 400, ["name"] = "Champagne 06" },
  [34] = { ["object"] = "prop_cherenkov_01", ["price"] = 80, ["name"] = "Vodka 01" },
  [35] = { ["object"] = "prop_cherenkov_02", ["price"] = 80, ["name"] = "Vodka 02" },
  [36] = { ["object"] = "prop_cherenkov_03", ["price"] = 80, ["name"] = "Vodka 03" },
  [37] = { ["object"] = "prop_cherenkov_04", ["price"] = 80, ["name"] = "Vodka 04" },
  [38] = { ["object"] = "prop_vodka_bottle", ["price"] = 80, ["name"] = "Vodka 05" },
  [39] = { ["object"] = "vodkarow", ["price"] = 850, ["name"] = "Vodka samling" },
  [40] = { ["object"] = "prop_tequila_bottle", ["price"] = 80, ["name"] = "Tequila 01" },
  [41] = { ["object"] = "prop_bar_shots", ["price"] = 150, ["name"] = "Tequila 02" },
  [42] = { ["object"] = "prop_bottle_cognac", ["price"] = 80, ["name"] = "Cognac" },
  [43] = { ["object"] = "prop_bottle_brandy", ["price"] = 80, ["name"] = "Brandy" },
  [44] = { ["object"] = "prop_whiskey_bottle", ["price"] = 80, ["name"] = "Whiskey 01" },
  [45] = { ["object"] = "prop_bottle_macbeth", ["price"] = 80, ["name"] = "Whiskey 02" },
  [46] = { ["object"] = "prop_bottle_richard", ["price"] = 80, ["name"] = "Whiskey 03" },
  [47] = { ["object"] = "spiritsrow", ["price"] = 650, ["name"] = "Spiritus samling 01" },
  [48] = { ["object"] = "prop_bikerset", ["price"] = 400, ["name"] = "Spiritus samling 02" },
  [49] = { ["object"] = "ng_proc_beerbottle_01a", ["price"] = 25, ["name"] = "Tom flaske 01" },
  [50] = { ["object"] = "ng_proc_brkbottle_02a", ["price"] = 25, ["name"] = "Tom flaske 02" },
  [51] = { ["object"] = "ng_proc_temp", ["price"] = 25, ["name"] = "Tom flaske 03" },
  [52] = { ["object"] = "p_amb_bag_bottle_01", ["price"] = 25, ["name"] = "Tom flaske 04" },
  [53] = { ["object"] = "p_whiskey_bottle_s", ["price"] = 30, ["name"] = "Tom flaske 05" },
  [54] = { ["object"] = "p_whiskey_notop", ["price"] = 30, ["name"] = "Tom flaske 06" },
  [55] = { ["object"] = "p_whiskey_notop_empty", ["price"] = 30, ["name"] = "Tom flaske 07" },
  [56] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 30, ["name"] = "Tom flaske 08" },
},


["Mad og Drikkelse"] = {
  [1] = { ["object"] = "prop_bar_nuts", ["price"] = 40, ["name"] = "Nødder 01" },
  [2] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 40, ["name"] = "Nødder 02" },
  [3] = { ["object"] = "prop_bowl_crisps", ["price"] = 50, ["name"] = "Chips" },
  [4] = { ["object"] = "prop_pineapple", ["price"] = 30, ["name"] = "Ananas" },
  [5] = { ["object"] = "prop_grapes_02", ["price"] = 75, ["name"] = "Vindruer" },
  [6] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "Frugtskål 01" },
  [7] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Frugtskål 02" },
  [8] = { ["object"] = "v_res_cakedome", ["price"] = 80, ["name"] = "Kage" },
  [9] = { ["object"] = "prop_candy_pqs", ["price"] = 50, ["name"] = "Slik 01" },
  [10] = { ["object"] = "prop_bar_beans", ["price"] = 40, ["name"] = "Slik 02" },
  [11] = { ["object"] = "prop_cs_bs_cup", ["price"] = 40, ["name"] = "Sodavand" },
  [12] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 60, ["name"] = "Doggybag 01" },
  [13] = { ["object"] = "prop_paper_bag_01", ["price"] = 45, ["name"] = "Doggybag 02" },
  [14] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Mixed korn" },
  [15] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Indkøbspose" },
  [16] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 100, ["name"] = "Askebæger" },
  [17] = { ["object"] = "prop_cigar_pack_01", ["price"] = 50, ["name"] = "Cigaretter 01" },
  [18] = { ["object"] = "prop_cigar_pack_02", ["price"] = 50, ["name"] = "Cigaretter 02" },
  [19] = { ["object"] = "prop_vend_fags_01", ["price"] = 1300, ["name"] = "Cigaret automat" },
  [20] = { ["object"] = "prop_vend_snak_01", ["price"] = 2500, ["name"] = "Slik automat" },
  [21] = { ["object"] = "prop_vend_soda_01", ["price"] = 2500, ["name"] = "Sodavands automat 01" },
  [22] = { ["object"] = "prop_vend_soda_02", ["price"] = 2500, ["name"] = "Sodavands automat 02" },
  [23] = { ["object"] = "prop_vend_water_01", ["price"] = 2000, ["name"] = "Vand automat" },
},


["Sport"] = {
  [1] = { ["object"] = "prop_yoga_mat_01", ["price"] = 150, ["name"] = "Yoga måtte 01" },
  [2] = { ["object"] = "prop_yoga_mat_02", ["price"] = 150, ["name"] = "Yoga måtte 02" },
  [3] = { ["object"] = "prop_yoga_mat_03", ["price"] = 150, ["name"] = "Yoga måtte 03" },
  [4] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 100, ["name"] = "Yoga måtte 04" },
  [5] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 100, ["name"] = "Yoga måtte 05" }, 
  [6] = { ["object"] = "prop_barbell_01", ["price"] = 200, ["name"] = "Vægt 01" },
  [7] = { ["object"] = "prop_barbell_02", ["price"] = 600, ["name"] = "Vægt 02" },
  [8] = { ["object"] = "prop_barbell_100kg", ["price"] = 600, ["name"] = "Vægt 03" },
  [9] = { ["object"] = "prop_barbell_10kg", ["price"] = 600, ["name"] = "Vægt 04" },
  [10] = { ["object"] = "prop_barbell_20kg", ["price"] = 600, ["name"] = "Vægt 05" },
  [11] = { ["object"] = "prop_barbell_30kg", ["price"] = 600, ["name"] = "Vægt 06" },
  [12] = { ["object"] = "prop_barbell_40kg", ["price"] = 600, ["name"] = "Vægt 07" },
  [13] = { ["object"] = "prop_barbell_50kg", ["price"] = 600, ["name"] = "Vægt 08" },
  [14] = { ["object"] = "prop_barbell_60kg", ["price"] = 600, ["name"] = "Vægt 09" },
  [15] = { ["object"] = "prop_weight_10k", ["price"] = 100, ["name"] = "Vægt 10" },
  [16] = { ["object"] = "prop_weight_15k", ["price"] = 100, ["name"] = "Vægt 11" },
  [17] = { ["object"] = "prop_weight_1_5k", ["price"] = 100, ["name"] = "Vægt 12" },
  [18] = { ["object"] = "prop_weight_20k", ["price"] = 100, ["name"] = "Vægt 13" },
  [19] = { ["object"] = "prop_weight_2_5k", ["price"] = 100, ["name"] = "Vægt 14" },
  [20] = { ["object"] = "prop_weight_5k", ["price"] = 100, ["name"] = "Vægt 15" },
  [21] = { ["object"] = "prop_weight_bench_02", ["price"] = 1200, ["name"] = "Træningsbænk" },
  [22] = { ["object"] = "prop_weight_squat", ["price"] = 2000, ["name"] = "Squat stativ" },
  [23] = { ["object"] = "prop_speedball_01", ["price"] = 400, ["name"] = "Boksebold" },
  [24] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 200, ["name"] = "Fodbold" },
  [25] = { ["object"] = "v_res_skateboard", ["price"] = 500, ["name"] = "Skateboard" },
},


["Musik"] = {
  [1] = { ["object"] = "prop_tapeplayer_01", ["price"] = 400, ["name"] = "Radio 01" },
  [2] = { ["object"] = "prop_boombox_01", ["price"] = 400, ["name"] = "Radio 02" },
  [3] = { ["object"] = "prop_portable_hifi_01", ["price"] = 600, ["name"] = "Radio 03" },
  [4] = { ["object"] = "prop_mp3_dock", ["price"] = 1000, ["name"] = "Radio 04" },
  [5] = { ["object"] = "v_res_mm_audio", ["price"] = 1500, ["name"] = "Radio 05" },
  [6] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 3000, ["name"] = "Jukebox" },
  [7] = { ["object"] = "prop_table_mic_01", ["price"] = 500, ["name"] = "Mikrofon 01" },
  [8] = { ["object"] = "v_ilev_fos_mic", ["price"] = 1500, ["name"] = "Mikrofon 02" },
  [9] = { ["object"] = "v_club_roc_micstd", ["price"] = 1500, ["name"] = "Mikrofon 03" },
  [10] = { ["object"] = "prop_amp_01", ["price"] = 2000, ["name"] = "Forstærker" },
  [11] = { ["object"] = "v_res_fh_speaker", ["price"] = 600, ["name"] = "Højtaler 01" },
  [12] = { ["object"] = "prop_speaker_02", ["price"] = 1000, ["name"] = "Højtaler 02" },
  [13] = { ["object"] = "prop_speaker_01", ["price"] = 1500, ["name"] = "Højtaler 03" },
  [14] = { ["object"] = "prop_speaker_03", ["price"] = 2000, ["name"] = "Højtaler 04" },
  [15] = { ["object"] = "prop_speaker_05", ["price"] = 2200, ["name"] = "Højtaler 05" },
  [16] = { ["object"] = "prop_speaker_06", ["price"] = 2500, ["name"] = "Højtaler 06" },
  [17] = { ["object"] = "prop_speaker_07", ["price"] = 3000, ["name"] = "Højtaler 07" },
  [18] = { ["object"] = "prop_speaker_08", ["price"] = 5000, ["name"] = "Højtaler 08" },
  [19] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 900, ["name"] = "Højtaler 09" },
  [20] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 1500, ["name"] = "Green Screen" },
  [21] = { ["object"] = "p_ld_sax", ["price"] = 30000, ["name"] = "Saxofon" },
  [22] = { ["object"] = "prop_bongos_01", ["price"] = 200, ["name"] = "Bongo trommer" },
  [23] = { ["object"] = "prop_acc_guitar_01", ["price"] = 1000, ["name"] = "Guitar" },
  [24] = { ["object"] = "prop_el_guitar_01", ["price"] = 5000, ["name"] = "El guitar 01" },
  [25] = { ["object"] = "prop_el_guitar_02", ["price"] = 7500, ["name"] = "El guitar 02" },
  [26] = { ["object"] = "prop_el_guitar_03", ["price"] = 6000, ["name"] = "El guitar 03" },
},
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
dropdowntable[category] = {}

for o,k in pairs(v) do

  local hash = GetHashKey(k.object)
  hashtable[hash] = k

  local id = k.object or "none"
  local name = k.name or "none"
  local price = k.price or 9999

  lookuptable[id] = k

  table.insert(dropdowntable[category],{id = id,name = name,price = price})
end 
end 

for k,v in pairs(furni.objects) do
for k,v in pairs(v) do
  v.id = v.object
end
end

if not Config.UsingNativeHousing then
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end

mLibs = exports["meta_libs"]